apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: parent-app
  project:
  source:
    repoURL: https://github.com/mocdaniel/gitops-examples
    targetRevision: HEAD
    path: apps
  syncPolicy:
    automated: {}
